# Completion for eix-sync (eix tools)
# Sync portage tree and update eix database

complete -c eix-sync -s h -d 'Help'
complete -c eix-sync -s '?' -d 'Help'
complete -c eix-sync -s i -d 'Ignore all previous options'
complete -c eix-sync -s s -r -d 'Rsync from SERVER; this implies -0'
complete -c eix-sync -s 2 -r -d 'Rsync to SERVER'
complete -c eix-sync -s 0 -d 'No eix -sync'
complete -c eix-sync -s U -d 'Do not touch database and omit @ hooks after eix-update'
complete -c eix-sync -s u -d 'Update database only and show differences. Equivalent to -0l@s ""'
complete -c eix-sync -s l -d 'Do not call layman or ! hooks'
complete -c eix-sync -s '@' -d 'Do not execute @ or @@ hooks'
complete -c eix-sync -s S -d 'Do not execute @ hooks after emerge --sync'
complete -c eix-sync -s M -d 'Run emerge -metadata'
complete -c eix-sync -s N -d 'Cancel previous -M'
complete -c eix-sync -s t -d 'Use temporary file to save current database'
complete -c eix-sync -s T -d 'Do not measure time'
complete -c eix-sync -s q -d 'Be quiet (close stdout)'
complete -c eix-sync -s w -d 'Run emerge-webrsync instead of emerge --sync'
complete -c eix-sync -s W -d 'Run emerge-delta-webrsync instead of emerge --sync'
complete -c eix-sync -s c -r -F -d 'Run CMD instead of emerge --sync'
complete -c eix-sync -s C -r -d 'Add OPT to emerge --sync'
complete -c eix-sync -s o -r -d 'Add OPT to eix-update'
complete -c eix-sync -s L -r -d 'Add OPT to layman'
complete -c eix-sync -s r -d 'Clear /var/cache/edb/dep/* before syncing'
complete -c eix-sync -s R -d 'Cancel previous -r'
complete -c eix-sync -s v -d 'Verbose'
complete -c eix-sync -s n -d 'Dry run; combine with -v'
complete -c eix-sync -s H -d 'No status line update'
