# Completion for eix-remote (eix tools)
# Update/manage remote overlays

complete -c eix-remote -s h -d 'Help'
complete -c eix-remote -s '?' -d 'Help'
complete -c eix-remote -s L -d 'Print LOCAL_LAYMAN and exit'
complete -c eix-remote -s k -d 'Keep permissions'
complete -c eix-remote -s K -d 'Keep permissions, resistant to -i'
complete -c eix-remote -s x -d 'Exclude local overlays which are remote'
complete -c eix-remote -s X -d 'Exclude remote overlays which are local'
complete -c eix-remote -s l -r -F -d 'Use PATH as LOCAL_LAYMAN'
complete -c eix-remote -s a -r -d 'Use ADDR as remote database'
complete -c eix-remote -s i -d 'Ignore all previous options'
complete -c eix-remote -s v -d 'Verbose (default)'
complete -c eix-remote -s H -d 'No status line update'
complete -c eix-remote -s q -d 'Quiet'

complete -c eix-remote -x -a 'update' -d 'Fetch eix-caches1 and add them to the eix database'
complete -c eix-remote -x -a 'update1' -d 'Fetch eix-caches1 and add them to the eix database'
complete -c eix-remote -x -a 'update2' -d 'Fetch eix-caches2 and add them to the eix database'
complete -c eix-remote -x -a 'add' -d 'Add fetched eix-caches1 to the eix database'
complete -c eix-remote -x -a 'add1' -d 'Add fetched eix-caches1 to the eix database'
complete -c eix-remote -x -a 'add2' -d 'Add fetched eix-caches2 to the eix database'
complete -c eix-remote -x -a 'fetch' -d 'Fetch eix-caches1'
complete -c eix-remote -x -a 'fetch1' -d 'Fetch eix-caches1'
complete -c eix-remote -x -a 'fetch2' -d 'Fetch eix-caches2'
complete -c eix-remote -x -a 'remove' -d 'Remove temporarily added virtual overlays from eix database'
